# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17 for publishing to GitHub Packages
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven Github Package
      run: mvn clean package spring-boot:repackage "-Drelease.version=${{  github.ref_name }} -Drepository.id=github -Drepository.url=https://maven.pkg.github.com/Murimi-Njiru/StrapiJ"

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml "-Drelease.version=${{  github.ref_name }}"
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Set up JDK 17 for publishing to Maven Central Repository
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Build with Maven Maven Package
      run: mvn clean package spring-boot:repackage "-Drelease.version=${{  github.ref_name }} -Drepository.id=ossrh -Drepository.url=https://oss.sonatype.org/service/local/staging/deploy/maven2/"
    - name: Publish to the Maven Central Repository
      run: mvn --batch-mode deploy "-Drelease.version=${{  github.ref_name }}"
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
